# Numpy Library - Numerical Python

In [1]:
import numpy as np 

In [2]:
# Whenever you import any library in python, that library is treated as an object.
# 2 features - Method and Attribute

In [3]:
# a = np.array() -method similiar to functions
# a.ndim - attribute are related to variables

In [6]:
a = np.array(1) # Method 
print(a)

1


In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
# Scalar - 0 Dimension
# Vector - 1 Dimension 
# Matrix - 2 Dimensions

In [8]:
a.ndim #Attribute

0

# Vector

In [10]:
list1 = [1,2,3,4]
print(list1)
print(type(list1))

[1, 2, 3, 4]
<class 'list'>


In [11]:
b = np.array([1,2,3,4])
print(b)

[1 2 3 4]


In [12]:
# 1. Numpy Arrays are faster
# 2. They have got lots of operations

In [13]:
b.ndim

1

# Matrix

In [17]:
c = np.array([[1,2,3],[4,5,9]])
print(c)

[[1 2 3]
 [4 5 9]]


In [18]:
c.ndim

2

In [19]:
print(c.size)

6


In [20]:
print(c.dtype)

int32


In [21]:
a = 1
type(a)

int

In [23]:
print(c.shape)

(2, 3)


# Other ways of creating arrays

In [24]:
d = np.arange(0,10,1)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
d.ndim

1

In [31]:
e = np.random.randint(0,10,20)
print(e)
print(e.size)

[9 6 7 9 1 5 3 0 6 0 5 7 7 6 4 1 9 3 7 3]
20


In [32]:
u = np.unique(e)
print(u)
print(u.size)

[0 1 3 4 5 6 7 9]
8


In [33]:
e.reshape(5,4)

array([[9, 6, 7, 9],
       [1, 5, 3, 0],
       [6, 0, 5, 7],
       [7, 6, 4, 1],
       [9, 3, 7, 3]])

In [35]:
e.reshape(10,2).astype('float32')

array([[9., 6.],
       [7., 9.],
       [1., 5.],
       [3., 0.],
       [6., 0.],
       [5., 7.],
       [7., 6.],
       [4., 1.],
       [9., 3.],
       [7., 3.]], dtype=float32)

In [36]:
e

array([9, 6, 7, 9, 1, 5, 3, 0, 6, 0, 5, 7, 7, 6, 4, 1, 9, 3, 7, 3])

In [37]:
e.sort()
e

array([0, 0, 1, 1, 3, 3, 3, 4, 5, 5, 6, 6, 6, 7, 7, 7, 7, 9, 9, 9])

In [42]:
e = np.append(e,90)
e

array([ 0,  0,  1,  1,  3,  3,  3,  4,  5,  5,  6,  6,  6,  7,  7,  7,  7,
        9,  9,  9, 90, 90])

In [43]:
np.power(e,2)

array([   0,    0,    1,    1,    9,    9,    9,   16,   25,   25,   36,
         36,   36,   49,   49,   49,   49,   81,   81,   81, 8100, 8100],
      dtype=int32)

In [40]:
np.sqrt(e)

array([0.        , 0.        , 1.        , 1.        , 1.73205081,
       1.73205081, 1.73205081, 2.        , 2.23606798, 2.23606798,
       2.44948974, 2.44948974, 2.44948974, 2.64575131, 2.64575131,
       2.64575131, 2.64575131, 3.        , 3.        , 3.        ])

In [46]:
x = np.ones(10,dtype = 'int32')
x

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [47]:
x.dtype

dtype('int32')

In [49]:
x_m = np.ones([10,10])
x_m # Image Processing - Pixels

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [50]:
x_m = np.zeros([10,10])
x_m

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
random_matrix = np.random.randint(0,10,size=(3,4))
random_matrix

array([[8, 3, 9, 2],
       [2, 3, 3, 7],
       [3, 2, 6, 8]])

In [52]:
random_matrix_t = random_matrix.T
random_matrix_t

array([[8, 2, 3],
       [3, 3, 2],
       [9, 3, 6],
       [2, 7, 8]])

In [53]:
# Mean
# Median
# Range
# Mode
# Max
# Min
# ArgMax
# Argmin

In [61]:
a = np.array([1,6,2,4,8,3,3])
print(np.mean(a))
print(np.median(a))
print(np.ptp(a))

3.857142857142857
3.0
7


In [62]:
from scipy import stats
stats.mode(a)

ModeResult(mode=array([3]), count=array([2]))

In [63]:
print(np.max(a))
print(np.min(a))

8
1


In [64]:
np.array(['Ameer','Xcelerator','NLP'])

array(['Ameer', 'Xcelerator', 'NLP'], dtype='<U10')